name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*' # Run only on version tags, e.g., v3.2.0

jobs:
  build-and-pack:
    runs-on: windows-latest  # Use the latest supported Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      - name: Restore Legacy NuGet Packages
        run: |
          nuget restore ./net47/RazorpayClient47.sln
          nuget restore ./net48/RazorpayClient48.sln

      - name: Build .NET Framework 4.7
        run: msbuild ./net47/RazorpayClient47.sln /p:Configuration=Release

      - name: Build .NET Framework 4.8
        run: msbuild ./net48/RazorpayClient48.sln /p:Configuration=Release
      
      - name: Restore and Build .NET 6.0
        run: dotnet build ./net6.0/RazorpayClient60.sln --configuration Release

      - name: Restore and Build .NET 8.0
        run: dotnet build ./net8.0/RazorpayClient80.sln --configuration Release

      - name: Get version from tag
        id: get_version
        run: |
          $VERSION = "${{ github.ref_name }}".Substring(1)
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Pack NuGet package
        run: nuget pack Razorpay.nuspec -Version ${{ env.VERSION }} -OutputDirectory ./nupkgs

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkgs/*.nupkg

  publish-nuget:
    needs: build-and-pack
    runs-on: ubuntu-latest
    
    steps:
      - name: Download NuGet package artifact
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkgs

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Push to NuGet
        run: dotnet nuget push "./nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}